<?php

use Illuminate\Database\Seeder;

class LinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $lines = [[
            "id"=>1,
            "sale" => 1,
            "pcs" => "584126992473",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "portabilidad",
            "ambit" => "digital",
        ],[
            "id"=>3,
            "sale" => 3,
            "pcs" => "584123122971",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "portabilidad",
            "ambit" => "digital",
        ],[
            "id"=>4,
            "sale" => 4,
            "pcs" => "584423322771",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "ninguno",
            "ambit" => "digital",
        ],[
            "id"=>5,
            "sale" => 5,
            "pcs" => "584143123671",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "bam",
            "ambit" => "digital",
        ],[
            "id"=>6,
            "sale" => 6,
            "pcs" => "5841257125824",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "bam",
            "ambit" => "digital",
        ],[
            "id"=>7,
            "sale" => 7,
            "pcs" => "5841257125824",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "bam",
            "ambit" => "digital",
        ],[
            "id"=>8,
            "sale" => 8,
            "pcs" => "5841257125824",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "bam",
            "ambit" => "digital",
        ],[
            "id"=>9,
            "sale" => 9,
            "pcs" => "5841257125824",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "bam",
            "ambit" => "digital",
        ],[
            "id"=>10,
            "sale" => 10,
            "pcs" => "5841257125824",
            "imei" => "",
            "sim" => "",
            "plan" => 1,
            "equipment" => 1,
            'plan_cost' => 14.53,
            'price' => 15,
            'fees' => 3,
            'chip_price' => 21.13,
            "substate" => 1,
            "donor_company" => "Entel",
            "type" => "bam",
            "ambit" => "digital",
        ]];

        DB::table('lines')->insert($lines);
    }
}
